// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signup.post').default>>>>
    }
    '/api/lessons/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lessons/[id].get').default>>>>
    }
    '/api/lessons': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lessons/index.get').default>>>>
    }
    '/api/progress/:userId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/progress/[userId].get').default>>>>
    }
    '/api/progress/save': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/progress/save.post').default>>>>
    }
    '/api/user/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/[id].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}