// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/22/2025, 3:08:59 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/tiannaalinalopes/projects/port-chops/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tiannaalinalopes/projects/port-chops/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tiannaalinalopes/projects/port-chops/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tiannaalinalopes/projects/port-chops/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tiannaalinalopes/projects/port-chops/plugins/**/*.{js,ts,mjs}","/Users/tiannaalinalopes/projects/port-chops/composables/**/*.{js,ts,mjs}","/Users/tiannaalinalopes/projects/port-chops/utils/**/*.{js,ts,mjs}","/Users/tiannaalinalopes/projects/port-chops/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tiannaalinalopes/projects/port-chops/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/tiannaalinalopes/projects/port-chops/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/tiannaalinalopes/projects/port-chops/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;